import '../core/models/audio_track.dart';
import '../core/models/spiritual_intent.dart';

class MockDataService {
  static final List<AudioTrack> sampleTracks = [
    AudioTrack(
      id: 'track_1',
      title: 'Atmosphere of Grace & Glory',
      artist: 'Nathaniel Bassey & LCM Worship',
      albumArtUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
      audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
      duration: const Duration(minutes: 5, seconds: 42),
      subgenre: 'Deep Worship',
      intentCategory: IntentCategory.deepWorship,
      mediaType: MediaType.song,
      isDownloaded: true,
      isFavorite: true,
      lyrics: const [
        LyricLine(timestampSeconds: 0, text: '[Instrumental Prelude]'),
        LyricLine(timestampSeconds: 12, text: 'Let your glory fill this sacred place'),
        LyricLine(timestampSeconds: 24, text: 'We bow in awe before your throne of grace'),
        LyricLine(timestampSeconds: 38, text: 'Holy Holy, Almighty is the Lord'),
        LyricLine(timestampSeconds: 52, text: 'Forever faithful is your holy word'),
        LyricLine(timestampSeconds: 70, text: 'Spirit move, break every heavy chain'),
        LyricLine(timestampSeconds: 88, text: 'Let your living water fall like rain'),
      ],
      notes: [
        SermonNote(
          id: 'note_1',
          timestampSeconds: 38,
          noteText: 'Key Revelation: Worship invites God\'s tangible presence into our daily battles.',
          createdAt: DateTime.now().subtract(const Duration(days: 1)),
        ),
      ],
    ),
    AudioTrack(
      id: 'track_2',
      title: 'Morning Mercies & Devotional Declaration',
      artist: 'Pastor Enoch Adeboye',
      albumArtUrl: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=800&q=80',
      audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
      duration: const Duration(minutes: 18, seconds: 30),
      subgenre: 'Spoken Sermon',
      intentCategory: IntentCategory.morningDevotion,
      mediaType: MediaType.sermon,
      isDownloaded: false,
      isFavorite: true,
      lyrics: const [
        LyricLine(timestampSeconds: 0, text: 'Welcome to this morning devotional broadcast.'),
        LyricLine(timestampSeconds: 15, text: 'Lamentations 3:22 tells us His mercies are new every morning.'),
        LyricLine(timestampSeconds: 40, text: 'Speak to your day before the sun rises above the horizon.'),
        LyricLine(timestampSeconds: 65, text: 'Declare: I am blessed, favored, and preserved by His covenant.'),
      ],
    ),
    AudioTrack(
      id: 'track_3',
      title: 'Warfare & Spiritual Breakthrough',
      artist: 'Apostle Joshua Selman',
      albumArtUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
      audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
      duration: const Duration(minutes: 25, seconds: 15),
      subgenre: 'Warfare Prayer',
      intentCategory: IntentCategory.warfarePrayers,
      mediaType: MediaType.sermon,
      isDownloaded: true,
      isFavorite: false,
      lyrics: const [
        LyricLine(timestampSeconds: 0, text: 'Lift up your heads, O ye gates!'),
        LyricLine(timestampSeconds: 20, text: 'Every stronghold contrary to your destiny is broken now.'),
        LyricLine(timestampSeconds: 45, text: 'The weapons of our warfare are not carnal, but mighty through God.'),
      ],
    ),
    AudioTrack(
      id: 'track_4',
      title: 'Silent Waters (Piano Meditation)',
      artist: 'LCM Instrumental Sanctuary',
      albumArtUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=800&q=80',
      audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
      duration: const Duration(minutes: 12, seconds: 05),
      subgenre: 'Soaking Instrumental',
      intentCategory: IntentCategory.studyFocus,
      mediaType: MediaType.song,
      isDownloaded: false,
      isFavorite: true,
      lyrics: const [
        LyricLine(timestampSeconds: 0, text: '[Calming Soaking Piano & Ambient Pads]'),
        LyricLine(timestampSeconds: 60, text: 'Be still and know that I am God. (Psalm 46:10)'),
      ],
    ),
    AudioTrack(
      id: 'track_5',
      title: 'Afrogospel Praise Celebration',
      artist: 'Moses Bliss & Mercy Chinwo',
      albumArtUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
      audioUrl: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
      duration: const Duration(minutes: 4, seconds: 50),
      subgenre: 'Afrogospel',
      intentCategory: IntentCategory.morningDevotion,
      mediaType: MediaType.song,
      isDownloaded: true,
      isFavorite: false,
      lyrics: const [
        LyricLine(timestampSeconds: 0, text: 'Joy in my heart, victory in my soul!'),
        LyricLine(timestampSeconds: 15, text: 'He has taken away my sorrow and turned it into praise.'),
        LyricLine(timestampSeconds: 32, text: 'Sing Hallelujah! The Lord reigneth!'),
      ],
    ),
  ];
}
